module.exports = {
  referenceSidebar: [
    'research/index',
    {type:'category',label:'Operational families',link:{type:'doc',id:'families/index'},items:[{type:'autogenerated',dirName:'families'}]},
    {type:'category',label:'Research chapters',items:[{type:'autogenerated',dirName:'research'}]},
    'visuals',
    'attack-activity-log-source-catalog',
    'attack-basic-detection-rule-catalog',
    'attack-statistical-anomaly-mapping',
    'statistical-anomaly-taxonomy',
    'security-log-source-taxonomy',
  ],
};
