import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import ResearchCover from '../ResearchCover';
import index from '../../data/research-index.json';
const routes=[
 ['Research and evidence','/research/','Read the consolidated foundations, incident analysis, telemetry contracts, and validation boundaries.'],
 ['Operational families','/families/','Fourteen practical views of unusual behavior, plus multi-event correlation.'],
 ['Activity-to-anomaly models','/attack-statistical-anomaly-mapping/','Compare an entity with an explicit expectation, then identify observable deviation.'],
 ['Statistical concepts','/statistical-anomaly-taxonomy/','Explore 118 overlapping statistical concepts without conflating them with operational families.'],
 ['Telemetry and collection','/security-log-source-taxonomy/','Browse 175 source categories and verify actual collection requirements.'],
 ['Rules and visual references','/attack-basic-detection-rule-catalog/','Inspect deterministic concepts alongside the evidence-linked visual library.'],
];
export default function AtlasHome(){return <Layout title="Anomaly Detection Atlas" description="One integrated reference for anomaly research, evidence-linked infographics, ATT&CK models, telemetry, simulation, and detection engineering.">
 <main>
  <header className="atlas-hero"><div className="container atlas-hero__content"><div className="atlas-eyebrow">1200km · Detection engineering</div><h1>Anomaly Detection Atlas</h1><p>From unusual activity to defensible evidence.</p><p className="atlas-hero-description">Research, illustrated explanations, statistical models, and collection requirements—connected to your tools, simulations, and detection workspaces.</p><div className="atlas-actions"><Link className="button button--primary button--lg" to="/research/">Start the research path</Link><Link className="button button--secondary button--lg" to="/attack-statistical-anomaly-mapping/">Find an anomaly model</Link></div></div></header>
  <section className="atlas-section"><div className="container"><h2>One reference, connected views</h2><p>An anomaly is an investigation lead, not a maliciousness verdict. Follow the evidence from explanation to collection and testing.</p><div className="atlas-route-grid">{routes.map(([title,to,body])=><article className="atlas-card" key={to}><h3><Link to={to}>{title}</Link></h3><p>{body}</p></article>)}</div></div></section>
  <section className="atlas-section atlas-section--surface"><div className="container atlas-two-column"><div><span className="atlas-kicker">Integrated research</span><h2>Malicious Activity as a Statistical Signal</h2><p>The revised research now lives within the Atlas as focused chapters and family pages. Its 55 current figures remain beside the explanations, with text equivalents and original source links.</p><p><Link to="/visuals/">Browse the visual index</Link> · <Link to="/research/provenance/">Read the evidence and migration scope</Link></p><p>The original article remains a publication snapshot; existing citations and deep links continue to work.</p></div><ResearchCover/></div></section>
  <section className="atlas-section"><div className="container"><h2>Choose the behavior you need to investigate</h2><p>These are operational feature families, not 15 mutually exclusive statistical classes. Correlation combines evidence from the other views.</p><div className="atlas-family-links">{index.families.map(f=><a key={f.id} href={f.url}>{f.title}</a>)}</div></div></section>
  <section className="atlas-section atlas-section--surface" id="ttp-modules"><div className="container"><h2>Continue into the security ecosystem</h2><p>Use <a href="https://1200km.com/ttp-simulation/telemetry/">Telemetry Library</a> pages to verify collection, <a href="https://1200km.com/ttp-simulation/detections/">Detection Rules</a> to inspect original rules and models, <a href="https://1200km.com/ttp-simulation/">Attack Simulations</a> for documented authorized-lab candidates, and <a href="https://1200km.com/ttp-simulation/tools/">Attack Tools</a> for tool references and existing guides.</p><p>Keep technique and actor context in the <a href="https://1200km.com/threat-matrix/">Threat Matrix</a>; use <a href="https://1200km.com/adversarygraph/">AdversaryGraph</a> for evidence-driven investigation. These connections do not imply successful live execution or detector effectiveness.</p><p><Link to="/attack-activity-log-source-catalog/">ATT&CK activity catalog</Link> · <a href="https://1200km.com/search.html">Search the ecosystem</a> · <a href="https://1200km.com/guides.html">Existing guides</a></p></div></section>
 </main></Layout>;}
